export enum HttpException {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,

  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  ALREADY_REPORTED = 208,
  IM_USED = 226,

  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,

  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const HttpExceptionMessages: Record<HttpException, string> = {
  [HttpException.CONTINUE]: 'Continue',
  [HttpException.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [HttpException.PROCESSING]: 'Processing',
  [HttpException.EARLY_HINTS]: 'Early Hints',

  [HttpException.OK]: 'OK',
  [HttpException.CREATED]: 'Created',
  [HttpException.ACCEPTED]: 'Accepted',
  [HttpException.NON_AUTHORITATIVE_INFORMATION]: 'Non-Authoritative Information',
  [HttpException.NO_CONTENT]: 'No Content',
  [HttpException.RESET_CONTENT]: 'Reset Content',
  [HttpException.PARTIAL_CONTENT]: 'Partial Content',
  [HttpException.MULTI_STATUS]: 'Multi-Status',
  [HttpException.ALREADY_REPORTED]: 'Already Reported',
  [HttpException.IM_USED]: 'IM Used',

  [HttpException.MULTIPLE_CHOICES]: 'Multiple Choices',
  [HttpException.MOVED_PERMANENTLY]: 'Moved Permanently',
  [HttpException.FOUND]: 'Found',
  [HttpException.SEE_OTHER]: 'See Other',
  [HttpException.NOT_MODIFIED]: 'Not Modified',
  [HttpException.USE_PROXY]: 'Use Proxy',
  [HttpException.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [HttpException.PERMANENT_REDIRECT]: 'Permanent Redirect',

  [HttpException.BAD_REQUEST]: 'Bad Request',
  [HttpException.UNAUTHORIZED]: 'Unauthorized',
  [HttpException.PAYMENT_REQUIRED]: 'Payment Required',
  [HttpException.FORBIDDEN]: 'Forbidden',
  [HttpException.NOT_FOUND]: 'Not Found',
  [HttpException.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [HttpException.NOT_ACCEPTABLE]: 'Not Acceptable',
  [HttpException.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [HttpException.REQUEST_TIMEOUT]: 'Request Timeout',
  [HttpException.CONFLICT]: 'Conflict',
  [HttpException.GONE]: 'Gone',
  [HttpException.LENGTH_REQUIRED]: 'Length Required',
  [HttpException.PRECONDITION_FAILED]: 'Precondition Failed',
  [HttpException.PAYLOAD_TOO_LARGE]: 'Payload Too Large',
  [HttpException.URI_TOO_LONG]: 'URI Too Long',
  [HttpException.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [HttpException.RANGE_NOT_SATISFIABLE]: 'Range Not Satisfiable',
  [HttpException.EXPECTATION_FAILED]: 'Expectation Failed',
  [HttpException.IM_A_TEAPOT]: "I'm a teapot",
  [HttpException.MISDIRECTED_REQUEST]: 'Misdirected Request',
  [HttpException.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [HttpException.LOCKED]: 'Locked',
  [HttpException.FAILED_DEPENDENCY]: 'Failed Dependency',
  [HttpException.TOO_EARLY]: 'Too Early',
  [HttpException.UPGRADE_REQUIRED]: 'Upgrade Required',
  [HttpException.PRECONDITION_REQUIRED]: 'Precondition Required',
  [HttpException.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [HttpException.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Request Header Fields Too Large',
  [HttpException.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',

  [HttpException.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [HttpException.NOT_IMPLEMENTED]: 'Not Implemented',
  [HttpException.BAD_GATEWAY]: 'Bad Gateway',
  [HttpException.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [HttpException.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [HttpException.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [HttpException.VARIANT_ALSO_NEGOTIATES]: 'Variant Also Negotiates',
  [HttpException.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [HttpException.LOOP_DETECTED]: 'Loop Detected',
  [HttpException.NOT_EXTENDED]: 'Not Extended',
  [HttpException.NETWORK_AUTHENTICATION_REQUIRED]: 'Network Authentication Required',
}
